// obdCxtStr.cpp

const char *obd_cxt_str[] = {
	"Supported PIDS",
	"Monitor status since DTCs cleared",
	"Freeze DTC",
	"Fuel system status",
	"Calculated engine load",
	"Engine coolant temperature",
	"Short term fuel trim - Bank 1",
	"Long term fuel trim - Bank 1",
	"Short term fuel trim - Bank 2",
	"Long term fuel trim - Bank 2",
	"Fuel pressure",
	"Intake manifold absolute pressure",
	"Engine RPM",
	"Vehicle speed",
	"Timing advance",
	"Intake air temperature",
	"MAF air flow rate",
	"Throttle position",
	"Commanded secondary air status",
	"Oxygen sensors present (in 2 banks)",
	"Oxygen Sensor 1",
	"Oxygen Sensor 2",
	"Oxygen Sensor 3",
	"Oxygen Sensor 4",
	"Oxygen Sensor 5",
	"Oxygen Sensor 6",
	"Oxygen Sensor 7",
	"Oxygen Sensor 8",
	"OBD standards this vehicle conforms to",
	"Oxygen sensors present (in 4 banks)",
	"Auxiliary input status",
	"Run time since engine start",
	"PIDs supported",
	"Distance traveled with malfunction indicator lamp (MIL) on",
	"Fuel Rail Pressure",
	"Fuel Rail Gauge Pressure",
	"Oxygen Sensor 1",
	"Oxygen Sensor 2",
	"Oxygen Sensor 3",
	"Oxygen Sensor 4",
	"Oxygen Sensor 5",
	"Oxygen Sensor 6",
	"Oxygen Sensor 7",
	"Oxygen Sensor 8",
	"Commanded EGR",
	"EGR Error",
	"Commanded evaporative purge",
	"Fuel Tank Level Input",
	"Warm-ups since codes cleared",
	"Distance traveled since codes cleared",
	"Evap. System Vapor Pressure",
	"Absolute Barometric Pressure",
	"Oxygen Sensor 1",
	"Oxygen Sensor 2",
	"Oxygen Sensor 3",
	"Oxygen Sensor 4",
	"Oxygen Sensor 5",
	"Oxygen Sensor 6",
	"Oxygen Sensor 7",
	"Oxygen Sensor 8",
	"Catalyst Temperature: Bank 1, Sensor 1",
	"Catalyst Temperature: Bank 2, Sensor 1",
	"Catalyst Temperature: Bank 1, Sensor 2",
	"Catalyst Temperature: Bank 2, Sensor 2",
	"PIDs supported",
	"Monitor status this drive cycle",
	"Control module voltage",
	"Absolute load value",
	"Fuel–Air commanded equivalence ratio",
	"Relative throttle position",
	"Ambient air temperature",
	"Absolute throttle position B",
	"Absolute throttle position C",
	"Accelerator pedal position D",
	"Accelerator pedal position E",
	"Accelerator pedal position F",
	"Commanded throttle actuator",
	"Time run with MIL on"
};
